### ISSUE TITLE
The site uses the old branding

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/centrucivic#47]
**Describe the bug**

The site uses the old branding for the images on the site.

- [ ] The favicon is using the old logo
- [ ] The old logo appears in the header
- [ ] The old logo appears on the about page
- [ ] The old NGO Hub logo in the about page

**Screenshots**

<img width="1117" alt="Screenshot 2024-03-04 at 15 49 05" src="https://github.com/code4romania/centrucivic/assets/2820084/ee980024-c688-4220-8935-0bd3881a2ef2">

<img width="970" alt="Screenshot 2024-03-04 at 15 52 35" src="https://github.com/code4romania/centrucivic/assets/2820084/43a7d21e-4714-4cdb-99fc-2345db5a4dfe">

<img width="130" alt="Screenshot 2024-03-04 at 15 52 49" src="https://github.com/code4romania/centrucivic/assets/2820084/4144e981-678b-45c2-8db6-57a1f90c924a">

**Comment by dragos1195** [comment]
@mirunaioana-msc please provide the correct logos in the Figma design https://figma.com/design/cfixQXmZ7FdFatiDCpUhyK/ONG-HUB?node-id=4087-45355&t=FtE87q1whA9U0pZl-0

**Comment by mirunaioana-msc** [comment]
Logos changed - https://www.figma.com/design/cfixQXmZ7FdFatiDCpUhyK/ONG-HUB?node-id=8202-18131&t=HS1Z3R4yX4XMAWMF-4
