### ISSUE TITLE
Issues with texts

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/centrucivic#48]
**Describe the bug**

Some texts have not been finished (i.e., they contain lorem ipsums, missing diacritics, and use wrong names)

- [ ] The about page [/about](https://www.centrucivic.ro/about)
- [ ] Search filters don't have diacritics
- [ ] `ONG Hub` appears in buttons/texts instead of `NGO Hub`
- [ ] Many diacritics are missing

**Screenshots**

<img width="1059" alt="Screenshot 2024-03-04 at 15 58 23" src="https://github.com/code4romania/centrucivic/assets/2820084/b003c5be-2c5b-47a4-961f-6df3c57c2eb9">

<img width="548" alt="Screenshot 2024-03-04 at 15 58 32" src="https://github.com/code4romania/centrucivic/assets/2820084/44d61375-dc04-45a7-b8ea-cd18671bc96f">

<img width="341" alt="Screenshot 2024-03-04 at 15 57 07" src="https://github.com/code4romania/centrucivic/assets/2820084/886afb2f-cbf8-45b2-97c4-bb9dcbe4a3b0">

<img width="1004" alt="Screenshot 2024-03-04 at 15 59 08" src="https://github.com/code4romania/centrucivic/assets/2820084/8d096df0-03ae-4255-aec1-e5ef68f83ba5">

<img width="1066" alt="Screenshot 2024-03-04 at 16 00 21" src="https://github.com/code4romania/centrucivic/assets/2820084/2790b719-9189-4919-af25-5bbd065e905f">

**Comment by dragos1195** [comment]
@mirunaioana-msc please provide the correct texts, including diacritics.

**Comment by mirunaioana-msc** [comment]
Despre Civic Center - https://www.figma.com/design/cfixQXmZ7FdFatiDCpUhyK/ONG-HUB?node-id=8202-18131&t=iQ5F2l0n0lbWmYFu-4
*pending new logo - @mirunaioana-msc

Pagina contact - https://www.figma.com/design/cfixQXmZ7FdFatiDCpUhyK/ONG-HUB?node-id=8206-18639&t=iQ5F2l0n0lbWmYFu-4

If you give me links to the json files I can add diacritics directly
